### ISSUE TITLE
'Electrometer concept' or 'Molecular electrometer'?

### ISSUE THREAD

**Issue by markussmiettinen** [NMRLipids/lipid_ionINTERACTION#22]
Currently we are referring to the effect of headgroup reorientation due to bound charge as the _electrometer concept_, and referring to the 1980's works by Joachim Seelig.

However, to me it seems that the term used by Seelig was _molecular electrometer_, first introduced in his [1987 Biochemistry paper](dx.doi.org/10.1021/bi00398a001).

Therefore, I would suggest we also refer to the phenomenon as _molecular electrometer_.

**Note.** One could also consider using _molecular electroscope_, as [electroscope](https://en.wikipedia.org/wiki/Electroscope) is probably the tool doing closest to what the headgroup here does. However, I recommend sticking to the nomenclature already established, especially as [electrometer](https://en.wikipedia.org/wiki/Electrometer) is also a valid word for the device.

**Comment by ohsOllila** [comment]
I agree on using "molecular electrometer" if this was the term Seelig used. I do not know why I have written electrometer concept. I think this term might have been used in some paper where this was used and I have adapted from there. But I think that it is better to use the same name which Seelig has used.

**Comment by markussmiettinen** [comment]
Ok. I made the changes to the manuscript and created a pull request.
