### ISSUE TITLE
TOC graphics is needed

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/lipid_ionINTERACTION#28]
If you have any suggestions for the TOC graphics, let us know.

**Comment by markussmiettinen** [comment]
I would like the TOC graphic to include a picture of a PC lipid, with classic [analog-display electrometers](http://www.kawaguchidenki.co.jp/eng/product/img/mma217b.jpg) drawn next to (or on top of) the alpha and beta carbons.

**Comment by ohsOllila** [comment]
Something like that has been done [here](http://dx.doi.org/10.1021/ja405200u).

**Comment by jmelcr** [comment]
I think this idea is just fitting. I'd place the electrometer-hand on the places of the measured OPs. The big lipid would be in a suppressed environment of a bilayer and water and ion solution.

**Comment by jmelcr** [comment]
I'll try to make a sketch today.

**Comment by jmelcr** [comment]
How about such a Fig?
![toc_nmrlip2](https://cloud.githubusercontent.com/assets/12782348/16449541/5ce108e6-3df8-11e6-88c2-8e011b850adb.png)

**Comment by markussmiettinen** [comment]
Very nice! Would it work with α -> S^α_CH and β -> S^β_CH ?

**Comment by jmelcr** [comment]
> Would it work with α -> S^α_CH and β -> S^β_CH ?

Yes, I'll change it, if it is accepted as a TOC, and after we collect here all suggestions/complaints/whatever.

**Comment by jmelcr** [comment]
Which of these shall I also add?
- [x] label for Phosphatidylcholine (or just PC resp POPC)
- [ ] gamma-meter
- [ ] "minus sign" in front of S^beta_CH so that both values decrease
- [ ] the title "Molecular electrometer concept"
- [ ] an arrow with the word "binding" connecting the bound Ca2+ with the electrometer

**Comment by markussmiettinen** [comment]
I would only add PC, none of the others.

**Comment by ohsOllila** [comment]
Thanks for the figure! I agree with Markus about additions.

**Comment by mattijavanainen** [comment]
The figure looks great, but here are a few very picky notes considering that most people see this on a low-dpi screen in small size: I would personally prefer to have the alpha and beta labels a bit larger. Also, the Ca2+ text could be more visible, by either a) making the white box less transparent b) placing the ion in the water phase together with others. The hands of the electrometer could also be more visible if similar white transparent mask is used for them as for the Ca2+ text.

**Comment by jmelcr** [comment]
OK, I get the point. I'll try adding some semi-transparent white background under the electrometer hands. 
alpha and beta hands will be increased to match the size of other labels.

**Comment by markussmiettinen** [comment]
Matti: _Ca2+ text could be more visible, by either a) making the white box less transparent b) placing the ion in the water phase together with others_

I would vote for option a), because having the ion in the membrane signals that we believe it does bind in real life, unlike Na+ and Cl-.

**Comment by jmelcr** [comment]
That was the reason why Ca2+ is in the membrane.

**Comment by jmelcr** [comment]
Update:
![toc_nmrlip2](https://cloud.githubusercontent.com/assets/12782348/16491926/10dc453a-3ee0-11e6-9fbe-beb37a9dcda2.png)

**Comment by mattijavanainen** [comment]
Almost perfect, but "CH" in the subscript should not be in italics.

**Comment by markussmiettinen** [comment]
Nice! How about leaving in just one ion of each type? That is, removing all but one of the Cl:s and Na:s? (I can see that you aim for total charge neutrality here, but I think we could relax on that one to make the figure less crowded.)

Tiny detail: I would write CH, instead of _CH_.

**Comment by jmelcr** [comment]
![toc_nmrlip2](https://cloud.githubusercontent.com/assets/12782348/16522585/11fdf624-3f9f-11e6-876c-57b72b4aef10.png)
and with less ions
![toc_nmrlip2_lessions](https://cloud.githubusercontent.com/assets/12782348/16522589/1d4645d6-3f9f-11e6-8d05-5c71a5b032bc.png)

**Comment by jmelcr** [comment]
Sorry, there's one extra Sodium..

**Comment by markussmiettinen** [comment]
Thanks! I like more the lower, i.e., with just one ion per species shown.

**Comment by jmelcr** [comment]
Corrected:
![toc_nmrlip2_lessions_corr](https://cloud.githubusercontent.com/assets/12782348/16523055/a803c4d0-3fa1-11e6-80ac-4a78df8fb5a4.png)
