### ISSUE TITLE
Figures 2 and 3 should be replaced by a figure comparing pure bilayers in full hydration?

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/lipid_ionINTERACTION#3]
I think that this figure could be removed. These are very unclear and I think would
be difficult to make more clearer. I am thinking that we could show the order
parameters for pure bilayer compared to experiments (as in the first paper) to
remind the quality different models without ions. And then show only the changes
as a function of ions, i.e. current Fig. 4.

**Comment by markussmiettinen** [comment]
I agree, these figures do not bring much.

Concerning showing the order parameters for a pure bilayer, I do not think it is needed. We could put it (or these figures 2 and 3) in the supplementary, and then refer to it/them from the caption of the figure that shows the changes as a function of ions.

I also would say it does not make much sense to show the glycerol S_CH:s as a function of ion concentrations, if we do not have experimental data to compare against (as now seems to be the case). Better would be to leave these out.

**Comment by ohsOllila** [comment]
Regarding the results without ions, it might be easier from the reader point of view that one does not have to go to the supplementary to check this figure. I also think that it is important to remember that the structures without ions are not exactly correct and also different in different force fields. Anyway, we can decide this later when we have decided which journal we are submitting and we know the length limitation.

Indeed, we have to think if we show or comment the glycerol backbone part or not. There is not much NMR data with ions on that. When reading old papers it seems to me that they did not bother to measure it since all the other results indicated that there would be no change. However, it seems now to me that there would be some changes in that region with some simulation models. Since measurement of these order parameters is now straightforward with 13C NMR, it is quite likely that at some point the data also for glycerol backbone becomes available. If we would report and discuss this it may even inspire someone to measure it. Anyway, this is something we have to think when the manuscript is progressing.

**Comment by markussmiettinen** [comment]
@ohsOllila's two points (it is easier for the reader to see the Figs in actual text, and it is important to remember that the actual structures are wrong) are true. However, as the structure without ions is not anymore our main focus here, we also could justifiably put these Figs to the SI, and just remind the reader about the wrong structures somewhere where it is **clearly visible, such as in the caption** of the Fig showing the ion effects. But true, we could wait now and only do this if we have a length limitation.

Concerning the glycerol order parameters. Should we try to ask around if someone has already measured these with salt, but just not bothered to publish? It would be a great asset to the manuscript to include these data.

**Comment by ohsOllila** [comment]
I have now left out the order parameters without ions. These are now discussed widely in NMRlipids I and NMRlipids V project so I think now that it is enough to cite those.

I have also left out the glycerol discussion completely. I think now that we should focus solely on the changes in alpha and beta, and their connection to ion binding.
