### ISSUE TITLE
New density plots.

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/lipid_ionINTERACTION#4]
I have made new density plots (Figs. 5 and 6). Let me know if there are suggestions, comments, etc. Or if you want to make new plot. All the data should be found from the Data folder, scripts to calculated the data from scripts folder and scripts for the current figures from Fig/scripts folder.

Fig 4: https://github.com/NMRLipids/lipid_ionINTERACTION/blob/master/Fig/NAdensities-eps-converted-to.pdf
Fig 5: https://github.com/NMRLipids/lipid_ionINTERACTION/blob/master/Fig/CAdensities-eps-converted-to.pdf

**Comment by ohsOllila** [comment]
I have now reorganized Fig. 3 to descending order according to the order parameter changes.

**Comment by ohsOllila** [comment]
For clarity I did put only the smallest available concentrations into the CaCl_2 density figure (currently Fig. 4). Figure with all concentrations is in supplementary material.

The densities calculated over the last 50ns are shown now for CHARMM with 350mM and 1000mM CaCl_2, however, I think we should use the last 100ns. Mykhailo, could you ran the script for the last 100ns?

**Comment by markussmiettinen** [comment]
There seems to be a bug in the density calculation, possibly due to the bilayer centering not working 100%. This leads to some smearing of the profiles. For example, CHARMM36 will have distinguishable peaks below 2 nm, when the smearing is removed.

Let us redo the plot with careful centering.

**Comment by markussmiettinen** [comment]
The plots were redone with careful centering, with the commit 2a7e9f6 finalizing the ion density distributions both in paper and in the ESI.
