### ISSUE TITLE
Simulation length in Slipids DPPC [NaCl]=850?

### ISSUE THREAD

**Issue by markussmiettinen** [NMRLipids/lipid_ionINTERACTION#48]
Looking at the trajectories provided in

https://zenodo.org/record/55322

it looks like to me that the 850 mM simulation trajectory is 200 ns, not 100 ns (as is the case for the 1750 and 2570 mM systems). Therefore, I changed the times in Table 1 as 105->205 and 100->200.

Is this correct, @jmelcr ?

**Comment by jmelcr** [comment]
I Will check it, these lines were already corrected, so some values might
have been changed to wrong values...

Dne 3. 10. 2016 13:10 napsal uživatel "Markus Miettinen" <
notifications@github.com>:

**Comment by jmelcr** [comment]
Correct, it is 200ns, I elongated this specific 850mM simulation. The other sims are just 100ns.

**Comment by markussmiettinen** [comment]
Excellent, thanks for confirming!
